"""
Tests for the ``getstate_setstate`` option of ``@attr.s`` and the Modern API
(``attrs.define`` etc.).

The assertions deliberately inspect class ``__dict__`` so that *whether* attrs
generated the methods is judged objectively instead of relying on pickle round
trips happening to work.  Classes that get pickled are defined at module scope
because pickle can only resolve classes that are importable by qualified name.
"""

from __future__ import absolute_import, division, print_function

import copy
import itertools
import pickle
import weakref

import pytest

import attr


try:
    import attrs as modern_attrs
except ImportError:  # pragma: no cover
    modern_attrs = None


pytestmark = pytest.mark.skipif(
    modern_attrs is None, reason="Modern API package is missing."
)
modern_available = pytest.mark.skipif(
    modern_attrs is None, reason="Modern API package is missing."
)

PROTOCOLS = list(range(pickle.HIGHEST_PROTOCOL + 1))

# The doc prefix attrs puts on every dunder method it generates via
# _add_method_dunders.
_AUTOGEN_DOC_PREFIX = "Method generated by attrs for class "


def _has_autogenerated(cls, name):
    """
    Return True if *cls* itself carries an attrs-generated *name* method.
    """
    meth = cls.__dict__.get(name)
    return (
        callable(meth)
        and meth.__name__ == name
        and (meth.__doc__ or "").startswith(_AUTOGEN_DOC_PREFIX)
    )


def roundtrip(obj, protocol=None):
    return pickle.loads(pickle.dumps(obj, protocol))


# ---------------------------------------------------------------------------
# Module-level classes used by the pickle tests.
# ---------------------------------------------------------------------------


@attr.s(slots=True)
class SlotDefault(object):
    x = attr.ib()
    y = attr.ib()


@attr.s
class DictDefault(object):
    x = attr.ib()


@attr.s(getstate_setstate=True)
class DictTrue(object):
    x = attr.ib()
    y = attr.ib(default=42)


@attr.s(slots=True, getstate_setstate=True)
class SlotTrue(object):
    x = attr.ib()
    y = attr.ib()


@attr.s(slots=True, getstate_setstate=True)
class SlotTrueMutableField(object):
    x = attr.ib()


@attr.s(slots=True, getstate_setstate=False)
class SlotFalseUser(object):
    x = attr.ib()

    def __getstate__(self):
        return ("custom", self.x)

    def __setstate__(self, state):
        tag, x = state
        assert tag == "custom"
        object.__setattr__(self, "x", x * 10)


@attr.s(slots=True, auto_detect=True)
class SlotAutoDetect(object):
    x = attr.ib()

    def __getstate__(self):
        return {"v": self.x + 100}

    def __setstate__(self, state):
        object.__setattr__(self, "x", state["v"])


@attr.s(slots=True, frozen=True, hash=True, getstate_setstate=True)
class FrozenDictTrue(object):
    x = attr.ib()


@attr.s(frozen=True, hash=True, getstate_setstate=True)
class PlainFrozenTrue(object):
    x = attr.ib()


@attr.s(frozen=True, hash=True)
class PlainFrozenDefault(object):
    x = attr.ib()


@attr.s(getstate_setstate=False)
class DictFalseNoMethods(object):
    x = attr.ib()


@attr.s(slots=True, frozen=True, cache_hash=True)
class SlotCacheHash(object):
    x = attr.ib()


@attr.s(frozen=True, hash=True, cache_hash=True, getstate_setstate=True)
class DictCacheHashTrue(object):
    x = attr.ib()


@attr.s(frozen=True, hash=True, cache_hash=True)
class DictCacheHashDefault(object):
    x = attr.ib()


@attr.s(slots=True, weakref_slot=True)
class WeakrefSlot(object):
    x = attr.ib()


@attr.s(slots=True)
class ExplicitWeakrefIb(object):
    __weakref__ = attr.ib(
        init=False, hash=False, repr=False, eq=False, order=False
    )


# Inheritance chains.


@attr.s(getstate_setstate=True)
class BaseDictTrue(object):
    a = attr.ib()


@attr.s(slots=True)
class ChildSlotsDefault(BaseDictTrue):
    b = attr.ib()


@attr.s(slots=True)
class BaseSlotsDefault(object):
    a = attr.ib()


@attr.s(getstate_setstate=True)
class ChildDictTrue(BaseSlotsDefault):
    b = attr.ib()


@attr.s(slots=True)
class Level1(object):
    x = attr.ib()


@attr.s(getstate_setstate=False)
class Level2(Level1):
    y = attr.ib()


@attr.s(slots=True)
class Level3(Level2):
    z = attr.ib()


@attr.s(slots=True, getstate_setstate=True)
class BothTrueBase(object):
    a = attr.ib()
    b = attr.ib()


@attr.s(slots=True, getstate_setstate=True)
class BothTrueChild(BothTrueBase):
    c = attr.ib()


@attr.s(slots=True, frozen=True, cache_hash=True)
class CacheHashBase(object):
    x = attr.ib()


@attr.s(slots=True, frozen=True)
class CacheHashChild(CacheHashBase):
    y = attr.ib()


# Frozen slots base with generated state + cache hash, dict child with
# generated state methods too.
@attr.s(getstate_setstate=True)
class DictChildOfCacheHash(CacheHashBase):
    y = attr.ib(default=99)


class _MultiBaseMixin(object):
    pass


@attr.s(slots=True, collect_by_mro=True)
class MultiBaseA(_MultiBaseMixin):
    a = attr.ib()


@attr.s(slots=True, collect_by_mro=True)
class MultiBaseB(MultiBaseA):
    b = attr.ib()


@attr.s(slots=True, collect_by_mro=True)
class MultiBaseD(MultiBaseB):
    c = attr.ib()
    d = attr.ib()


# Base-class protocol takeover.


class _ProtocolBase(object):
    def __getstate__(self):
        return {"z": self._z * 2}

    def __setstate__(self, state):
        object.__setattr__(self, "_z", state["z"])


@attr.s(slots=True, getstate_setstate=False, init=False)
class ProtocolChild(_ProtocolBase):
    _z = attr.ib()

    def __init__(self, z):
        object.__setattr__(self, "_z", z)


# Non-slots custom methods.


@attr.s(eq=True, getstate_setstate=False)
class DictFalseUser(object):
    x = attr.ib()

    def __getstate__(self):
        return self.__dict__

    def __setstate__(self, state):
        state["x"] *= 5
        self.__dict__.update(state)


# Matrix classes: slots x frozen x cache_hash.
_MATRIX_CONFIGS = [
    vals
    for vals in itertools.product([True, False], repeat=3)
    if not vals[2] or vals[1]  # cache_hash needs hashing (frozen -> hash)
]


@attr.s(
    slots=True, frozen=True, cache_hash=True, getstate_setstate=True,
    eq=True, hash=True,
)
class MatrixC_111(object):
    x = attr.ib()
    y = attr.ib(default="hi")


@attr.s(
    slots=True, frozen=True, cache_hash=False, getstate_setstate=True,
    eq=True, hash=True,
)
class MatrixC_110(object):
    x = attr.ib()
    y = attr.ib(default="hi")


@attr.s(
    slots=True, frozen=False, cache_hash=False, getstate_setstate=True,
    eq=True, hash=True,
)
class MatrixC_100(object):
    x = attr.ib()
    y = attr.ib(default="hi")


@attr.s(
    slots=False, frozen=True, cache_hash=True, getstate_setstate=True,
    eq=True, hash=True,
)
class MatrixC_011(object):
    x = attr.ib()
    y = attr.ib(default="hi")


@attr.s(
    slots=False, frozen=True, cache_hash=False, getstate_setstate=True,
    eq=True, hash=True,
)
class MatrixC_010(object):
    x = attr.ib()
    y = attr.ib(default="hi")


@attr.s(
    slots=False, frozen=False, cache_hash=False, getstate_setstate=True,
    eq=True, hash=True,
)
class MatrixC_000(object):
    x = attr.ib()
    y = attr.ib(default="hi")


_MATRIX_CLASSES = [
    (globals()["MatrixC_%d%d%d" % vals], dict(zip(("slots", "frozen", "cache_hash"), vals)))
    for vals in _MATRIX_CONFIGS
]


# Modern API classes (guarded so the module can be collected without the
# Modern API package).
if modern_attrs is not None:

    @modern_attrs.frozen
    class ModernFrozen(object):
        x: int

    @modern_attrs.frozen(cache_hash=True)
    class ModernFrozenCache(object):
        x: int

    @modern_attrs.frozen(getstate_setstate=False)
    class ModernFrozenFalse(object):
        x: int

        def __getstate__(self):
            return {"custom": self.x}

        def __setstate__(self, state):
            object.__setattr__(self, "x", state["custom"])

    @modern_attrs.frozen
    class ModernChainBase(object):
        a: int

    @modern_attrs.define
    class ModernChainChild(ModernChainBase):
        b: int

    @modern_attrs.frozen
    class ModernML1(object):
        x: int

    @modern_attrs.frozen
    class ModernML2(ModernML1):
        y: int

    @modern_attrs.frozen
    class ModernML3(ModernML2):
        z: int


# ---------------------------------------------------------------------------
# Tests.
# ---------------------------------------------------------------------------


class TestDefaultBehavior(object):
    """
    The None default keeps the historical behavior.
    """

    def test_slots_generated_by_default(self):
        assert _has_autogenerated(SlotDefault, "__getstate__")
        assert _has_autogenerated(SlotDefault, "__setstate__")

    def test_non_slots_not_generated_by_default(self):
        assert "__getstate__" not in DictDefault.__dict__
        assert "__setstate__" not in DictDefault.__dict__

    def test_non_slots_default_pickles_dict(self):
        c = DictDefault(1)
        c.extra = 2

        c2 = roundtrip(c)

        assert c2.x == 1
        assert c2.extra == 2

    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_slots_default_roundtrips(self, protocol):
        assert roundtrip(SlotDefault(1, 2), protocol) == SlotDefault(1, 2)


class TestExplicitTrue(object):
    def test_non_slots_generates_methods(self):
        assert _has_autogenerated(DictTrue, "__getstate__")
        assert _has_autogenerated(DictTrue, "__setstate__")

    def test_non_slots_state_is_exactly_the_attrs_fields(self):
        assert DictTrue(1).__getstate__() == (1, 42)

    def test_non_slots_extra_dict_state_dropped(self):
        c = DictTrue(1)
        c.extra = "nope"

        assert c.__getstate__() == (1, 42)
        assert not hasattr(roundtrip(c), "extra")

    @pytest.mark.parametrize("protocol", PROTOCOLS)
    @pytest.mark.parametrize("cls", [DictTrue, SlotTrue])
    def test_roundtrips_all_protocols(self, cls, protocol):
        assert roundtrip(cls(1, "a"), protocol) == cls(1, "a")

    def test_copy_and_deepcopy(self):
        c = SlotTrueMutableField([1])
        assert copy.copy(c) == c
        assert copy.deepcopy(c) == c
        assert copy.deepcopy(c).x is not c.x

    def test_explicit_true_overrides_user_methods(self):
        """
        True means "attrs, you generate them" -- including overriding methods
        defined in the class body.  Checked on both layouts via a non-pickle
        local class.
        """

        @attr.s(slots=True, getstate_setstate=True)
        class C(object):
            x = attr.ib()

            def __getstate__(self):
                return "user"

        assert _has_autogenerated(C, "__getstate__")
        assert C(8).__getstate__() == (8,)

        @attr.s(getstate_setstate=True)
        class D(object):
            x = attr.ib()

            def __getstate__(self):
                return "user"

        assert _has_autogenerated(D, "__getstate__")
        assert D(8).__getstate__() == (8,)


class TestExplicitFalse(object):
    def test_slots_methods_absent_from_class_dict(self):
        assert "__getstate__" not in SlotFalseUser.__dict__ or (
            SlotFalseUser.__dict__["__getstate__"].__doc__ is None
        )
        # Objectively the user's function survived, attrs did not install one.
        assert not _has_autogenerated(SlotFalseUser, "__getstate__")
        assert not _has_autogenerated(SlotFalseUser, "__setstate__")

    def test_non_slots_methods_absent(self):
        @attr.s(getstate_setstate=False)
        class C(object):
            x = attr.ib()

        assert "__getstate__" not in C.__dict__
        assert "__setstate__" not in C.__dict__

    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_user_methods_take_over_slots(self, protocol):
        assert roundtrip(SlotFalseUser(2), protocol).x == 20

    def test_user_methods_take_over_non_slots(self):
        assert copy.copy(DictFalseUser(5)) == DictFalseUser(25)

    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_base_class_protocol_takes_over(self, protocol):
        c = ProtocolChild(10)
        assert c.__getstate__() == {"z": 20}
        assert roundtrip(c, protocol)._z == 20

    def test_invalid_value_raises(self):
        with pytest.raises(TypeError):

            @attr.s(getstate_setstate="yes")
            class C(object):
                x = attr.ib()

    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_no_methods_no_protocol_non_slots_uses_default_pickle(
        self, protocol
    ):
        c = DictFalseNoMethods(3)
        c.foo = 4
        c2 = roundtrip(c, protocol)
        assert c2.x == 3 and c2.foo == 4


class TestAutoDetect(object):
    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_slots_user_methods_kept_with_auto_detect(self, protocol):
        assert not _has_autogenerated(SlotAutoDetect, "__getstate__")
        assert not _has_autogenerated(SlotAutoDetect, "__setstate__")
        assert roundtrip(SlotAutoDetect(1), protocol).x == 101

    def test_slots_user_getstate_only_kept(self):
        @attr.s(slots=True, auto_detect=True)
        class C(object):
            x = attr.ib()

            def __getstate__(self):
                return {"x": self.x}

        assert not _has_autogenerated(C, "__getstate__")

    def test_without_auto_detect_slots_user_methods_are_replaced(self):
        """
        Historical behavior: without auto_detect attrs always generates the
        methods for slotted classes.
        """

        @attr.s(slots=True)
        class C(object):
            x = attr.ib()

            def __getstate__(self):
                return ("boom",)

            def __setstate__(self, state):
                pass

        assert _has_autogenerated(C, "__getstate__")
        assert C(5).__getstate__() == (5,)


class TestFrozen(object):
    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_frozen_slots_roundtrip_does_not_use_setattr(self, protocol):
        c = roundtrip(FrozenDictTrue(5), protocol)

        assert c.x == 5
        with pytest.raises(attr.exceptions.FrozenInstanceError):
            c.x = 6

    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_frozen_non_slots_roundtrip(self, protocol):
        c = roundtrip(PlainFrozenTrue(5), protocol)
        assert c.x == 5
        with pytest.raises(attr.exceptions.FrozenInstanceError):
            c.x = 6

    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_frozen_non_slots_default_dict_restore(self, protocol):
        """
        Frozen dict classes without generated methods still restore through
        pickle's default machinery without tripping __setattr__.
        """
        assert roundtrip(PlainFrozenDefault(7), protocol).x == 7


class TestWeakref(object):
    def test_weakref_slot_not_part_of_state(self):
        c = WeakrefSlot(1)
        assert weakref.ref(c)() is c
        assert c.__getstate__() == (1,)

    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_weakref_slot_roundtrip(self, protocol):
        c2 = roundtrip(WeakrefSlot(3), protocol)
        assert c2.x == 3
        assert weakref.ref(c2)() is c2

    def test_explicit_weakref_ib_excluded(self):
        assert ExplicitWeakrefIb().__getstate__() == ()
        assert copy.deepcopy(ExplicitWeakrefIb()) == ExplicitWeakrefIb()

    def test_weakref_excluded_when_generated_for_non_slots(self):
        assert DictTrue(1).__getstate__() == (1, 42)


class TestCacheHash(object):
    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_slots_cache_hash_not_serialized(self, protocol):
        c = SlotCacheHash(11)
        h = hash(c)
        assert getattr(c, "_attrs_cached_hash") is not None

        assert c.__getstate__() == (11,)

        c2 = roundtrip(c, protocol)
        # Reset, not restored from a stale serialized value.
        assert c2._attrs_cached_hash is None
        assert hash(c2) == h

    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_non_slots_generated_cache_hash_reset(self, protocol):
        c = DictCacheHashTrue(12)
        h = hash(c)

        c2 = roundtrip(c, protocol)
        assert c2.__getstate__() == (12,)
        assert c2._attrs_cached_hash is None
        assert hash(c2) == h

    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_non_slots_default_cache_hash_wrapper(self, protocol):
        c = DictCacheHashDefault(13)
        hash(c)

        c2 = roundtrip(c, protocol)
        assert c2._attrs_cached_hash is None

    def test_setstate_detection_uses_hash_defaults(self):
        from attr._make import _is_cache_hash_class

        assert _is_cache_hash_class(CacheHashBase)
        # The child gets its own non-caching frozen hash.
        assert not _is_cache_hash_class(CacheHashChild)
        # No slot for the cache on the child; setstate must not blow up.
        c2 = roundtrip(CacheHashChild(1, 2))
        assert (c2.x, c2.y) == (1, 2)

    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_dict_child_of_cached_slots_base(self, protocol):
        obj = DictChildOfCacheHash(1, 2)
        rt = roundtrip(obj, protocol)
        assert (rt.x, rt.y) == (1, 2)
        # The stale cache from the base never travels in the tuple state.
        assert rt.__getstate__() == (1, 2)


class TestInheritance(object):
    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_non_slots_true_parent_slots_default_child(self, protocol):
        obj = ChildSlotsDefault(1, 2)

        # No duplicated inherited field, no missing new field.
        assert obj.__getstate__() == (1, 2)
        assert BaseDictTrue(9).__getstate__() == (9,)

        rt = roundtrip(obj, protocol)
        assert (rt.a, rt.b) == (1, 2)

    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_slots_default_parent_non_slots_true_child(self, protocol):
        obj = ChildDictTrue(3, 4)
        assert obj.__getstate__() == (3, 4)
        assert BaseSlotsDefault(9).__getstate__() == (9,)

        rt = roundtrip(obj, protocol)
        assert (rt.a, rt.b) == (3, 4)

    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_three_levels_mixed_off_in_middle(self, protocol):
        obj = Level3(1, 2, 3)
        assert obj.__getstate__() == (1, 2, 3)

        rt = roundtrip(obj, protocol)
        assert (rt.x, rt.y, rt.z) == (1, 2, 3)

        # L2 falls back to the base slots protocol.
        rt2 = roundtrip(Level2(4, 5), protocol)
        assert (rt2.x, rt2.y) == (4, 5)

    def test_parent_and_child_both_true_no_duplication(self):
        assert BothTrueBase(1, 2).__getstate__() == (1, 2)
        assert BothTrueChild(1, 2, 3).__getstate__() == (1, 2, 3)

        rt = roundtrip(BothTrueChild(1, 2, 3))
        assert (rt.a, rt.b, rt.c) == (1, 2, 3)

    def test_multiple_base_attrs_collected_once(self):
        """
        Fields inherited across several attrs levels appear once in state.
        """
        obj = MultiBaseD(1, 2, 3, 4)
        assert obj.__getstate__() == (1, 2, 3, 4)
        rt = roundtrip(obj)
        assert (rt.a, rt.b, rt.c, rt.d) == (1, 2, 3, 4)


class TestMatrix(object):
    """
    Cartesian product of the class-shaping options with generated methods.
    """

    @pytest.mark.parametrize("cls,kwargs", _MATRIX_CLASSES)
    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_generated_methods_roundtrip(self, cls, kwargs, protocol):
        assert _has_autogenerated(cls, "__getstate__")
        assert _has_autogenerated(cls, "__setstate__")

        rt = roundtrip(cls(1), protocol)
        assert rt == cls(1)
        if kwargs["frozen"]:
            with pytest.raises(attr.exceptions.FrozenInstanceError):
                rt.x = 2


class TestMakeClassAndDataclass(object):
    def test_make_class_passes_option_false(self):
        C = attr.make_class(
            "MakeClassFalseLocal", ["x"], slots=True, getstate_setstate=False
        )
        assert "__getstate__" not in C.__dict__

    def test_make_class_true(self):
        C = attr.make_class("MakeClassTrueG", ["x"], getstate_setstate=True)
        assert _has_autogenerated(C, "__getstate__")
        assert C(x=1).__getstate__() == (1,)
        # make_class points __module__ at the calling frame which pytest's
        # import machinery cannot resolve for pickle; copy.copy exercises the
        # same state protocol.
        assert copy.copy(C(x=1)) == C(x=1)

    def test_dataclass(self):
        @attr.dataclass(getstate_setstate=True)
        class C(object):
            x: int

        assert _has_autogenerated(C, "__getstate__")
        assert copy.copy(C(1)) == C(1)


@modern_available
class TestModernApi(object):
    def test_define_default_non_slots_no_methods(self):
        @modern_attrs.define
        class C(object):
            x: int

        assert not _has_autogenerated(C, "__getstate__")
        assert "__slots__" not in C.__dict__

    def test_frozen_default_slots_generates_methods(self):
        assert "__slots__" in ModernFrozen.__dict__
        assert _has_autogenerated(ModernFrozen, "__getstate__")
        assert _has_autogenerated(ModernFrozen, "__setstate__")
        assert roundtrip(ModernFrozen(1)).x == 1

    def test_frozen_is_immutable(self):
        with pytest.raises(attr.exceptions.FrozenInstanceError):
            ModernFrozen(1).x = 2

    def test_frozen_weakrefable_by_default(self):
        assert weakref.ref(ModernFrozen(1))() is not None

    def test_define_explicit_true(self):
        @modern_attrs.define(getstate_setstate=True)
        class C(object):
            x: int

        assert _has_autogenerated(C, "__getstate__")
        assert C(9).__getstate__() == (9,)

    def test_frozen_explicit_false_user_methods_take_over(self):
        assert not _has_autogenerated(ModernFrozenFalse, "__getstate__")
        assert roundtrip(ModernFrozenFalse(4)).x == 4

    def test_define_auto_detect_user_getstate_kept_slots(self):
        @modern_attrs.define(slots=True)
        class C(object):
            x: int

            def __getstate__(self):
                return {"x": self.x * 3}

            def __setstate__(self, state):
                object.__setattr__(self, "x", state["x"])

        assert not _has_autogenerated(C, "__getstate__")

    def test_frozen_cache_hash_roundtrip(self):
        c = ModernFrozenCache(5)
        h = hash(c)
        rt = roundtrip(c)
        assert rt._attrs_cached_hash is None
        assert hash(rt) == h

    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_inheritance_dict_child_of_frozen_slots_base(self, protocol):
        rt = roundtrip(ModernChainChild(1, 2), protocol)
        assert (rt.a, rt.b) == (1, 2)

    @pytest.mark.parametrize("protocol", PROTOCOLS)
    def test_multi_level_mixed(self, protocol):
        rt = roundtrip(ModernML3(1, 2, 3), protocol)
        assert (rt.x, rt.y, rt.z) == (1, 2, 3)

    def test_field_factory(self):
        @modern_attrs.define
        class C(object):
            x: list = modern_attrs.field(factory=list)

        assert C().x == []
        assert C().x is not C().x

    def test_mutable_alias_is_define(self):
        @modern_attrs.mutable
        class C(object):
            x: int

        c = C(1)
        c.x = 2
        assert c.x == 2

    def test_make_class(self):
        C = modern_attrs.make_class(
            "ModernMakeClassCLocal",
            {"x": attr.ib()},
            getstate_setstate=True,
        )
        assert _has_autogenerated(C, "__getstate__")
        assert C(x=1).__getstate__() == (1,)
        assert copy.copy(C(x=1)) == C(x=1)
